# Generated by Django 3.2.9 on 2021-11-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=100)),
                ('nation_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='renter',
            fields=[
                ('renter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fathers_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('permanent_address', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('nation_id', models.CharField(max_length=100)),
                ('emergancy_name', models.CharField(max_length=200)),
                ('emergancy_phone', models.CharField(max_length=200)),
                ('rented_flat_number', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('owner_referal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.owner')),
            ],
        ),
    ]
