# Generated by Django 3.1.7 on 2021-11-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flat_details',
            fields=[
                ('flat_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_amount', models.FloatField()),
                ('size', models.CharField(max_length=100)),
                ('flat_number', models.CharField(max_length=50)),
                ('flat_floor_number', models.CharField(max_length=10)),
                ('flat_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.owner')),
                ('flat_renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='remain',
            fields=[
                ('remaining_id', models.AutoField(primary_key=True, serialize=False)),
                ('remained_amount', models.FloatField()),
                ('notes', models.TextField(max_length=500)),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.flat_details')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.owner')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barivara_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='earning',
            fields=[
                ('earning_id', models.AutoField(primary_key=True, serialize=False)),
                ('earning_date', models.DateField()),
                ('rent_of_month_year', models.CharField(max_length=100)),
                ('earned_amount', models.FloatField()),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.flat_details')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.owner')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barivara_app.renter')),
            ],
        ),
    ]
