# Generated by Django 3.2.9 on 2021-11-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0003_owner_referal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='rented_flat_number',
        ),
    ]
