# Generated by Django 3.2.9 on 2021-11-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0005_alter_owner_referal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_details',
            name='flat_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
