# Generated by Django 3.2.9 on 2021-11-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0006_flat_details_flat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_details',
            name='flat_renter_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='barivara_app.renter'),
        ),
    ]
