# Generated by Django 3.2.9 on 2021-12-02 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0008_flat_details_flat_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='earning_month',
            field=models.CharField(null=True, max_length=10),
        ),
        migrations.AddField(
            model_name='remain',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='remain',
            name='remain_month',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
