# Generated by Django 3.2.9 on 2021-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0009_auto_20211202_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='earning_month',
            field=models.CharField(null=True,max_length=10),
        ),
    ]
