# Generated by Django 3.1.7 on 2021-12-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0016_remain_earning_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remain',
            name='earning_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barivara_app.earning'),
        ),
    ]
