# Generated by Django 3.1.7 on 2021-12-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barivara_app', '0018_flat_details_is_rented'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_for_rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.flat_details')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barivara_app.renter')),
            ],
        ),
    ]
